server:
  port: 8000
  servlet:
    context-path: /api
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: mscloud-files
  profiles:
    active: test

mscloud:
  minio:
    endpoint: 
    bucketName: 
    accessKey: 
    secretKey: 
  oss:
    endpoint:
    bucketName:
    accessKey:
    secretKey:
  ftp:
    ip:
    port: 21
    username:
    password:
    workDir:
